Fixed unicode breakage.
slugify() requires unicode, not a str instance. This causes the extension to
crash:

File "/home/erik/virtualenv/bb/local/lib/python2.7/site-packages/markdown/__init__.py" in markdown
  386.     return md.convert(text)
File "/home/erik/virtualenv/bb/local/lib/python2.7/site-packages/markdown/__init__.py" in convert
  287.             newRoot = treeprocessor.run(root)
File "/home/erik/virtualenv/bb/local/lib/python2.7/site-packages/markdown/extensions/headerid.py" in run
  140.                         id = slugify(''.join(itertext(elem)), sep)
File "/home/erik/virtualenv/bb/local/lib/python2.7/site-packages/markdown/extensions/headerid.py" in slugify
  93.     value = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore')

TypeError: must be unicode, not str