Fenced_code should get the first element of each code_hilite conf option
This should fix this issue: https://github.com/waylan/Python-Markdown/issues/60

I suspect this error is an artifact of the extension API change. Before
this commit, fenced_code would get a list and return an error like:

pygments.util.OptionError: Invalid type [False, 'Use inline styles
instead of CSS classes - Default false'] for option noclasses; use 1/0,
yes/no, true/false, on/off

because it was getting a list where it was expecting a boolean.